### ISSUE TITLE
KeyError: 'token_prediction'

### ISSUE THREAD

**Issue by bg428** [violet-zct/fairseq-detect-hallucination#1]
Trying to load the pretrained [Roberta checkpoint](https://dl.fbaipublicfiles.com/detect-hallucination/xsum.roberta.tar.gz) for xsum. But there is a KeyError while loading the model.
The model_name_or_path, checkpoint_file, and data_name_or_path was set.

```
Traceback (most recent call last):
  File "load.py", line 6, in <module>
    data_name_or_path='/usr/local/Downloads/xsum/data'
  File "/usr/local/lib/python3.7/dist-packages/fairseq/models/roberta/model.py", line 251, in from_pretrained
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/fairseq/hub_utils.py", line 72, in from_pretrained
    arg_overrides=kwargs,
  File "/usr/local/lib/python3.7/dist-packages/fairseq/checkpoint_utils.py", line 279, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/usr/local/lib/python3.7/dist-packages/fairseq/checkpoint_utils.py", line 232, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/usr/local/lib/python3.7/dist-packages/fairseq/checkpoint_utils.py", line 439, in _upgrade_state_dict
    cls = REGISTRY["registry"][choice]
KeyError: 'token_prediction'
```

**Comment by Lyshc-cgc** [comment]
I also have this prolem.!! Could you please sovle this issue for us?@violet-zct 
Is this repo really base on fairseq(tag v0.7.0)? There are a lot of places in your code that are obviously not using version v0.7.0。For example like `from fairseq.models.roberta import RobertaModel`, but we can check tags in fairseq repo and know that roberta model that has only existed since v0.8.0, that means we can only use  `from fairseq.models.roberta import RobertaModel` using at least fairseq v0.8.0.

**Comment by violet-zct** [comment]
Hey, thanks for raising this problem! I corrected it to be 0.9.0.

**Comment by Lyshc-cgc** [comment]
> Trying to load the pretrained [Roberta checkpoint](https://dl.fbaipublicfiles.com/detect-hallucination/xsum.roberta.tar.gz) for xsum. But there is a KeyError while loading the model. The model_name_or_path, checkpoint_file, and data_name_or_path was set.
> 
> ```
> Traceback (most recent call last):
>   File "load.py", line 6, in <module>
>     data_name_or_path='/usr/local/Downloads/xsum/data'
>   File "/usr/local/lib/python3.7/dist-packages/fairseq/models/roberta/model.py", line 251, in from_pretrained
>     **kwargs,
>   File "/usr/local/lib/python3.7/dist-packages/fairseq/hub_utils.py", line 72, in from_pretrained
>     arg_overrides=kwargs,
>   File "/usr/local/lib/python3.7/dist-packages/fairseq/checkpoint_utils.py", line 279, in load_model_ensemble_and_task
>     state = load_checkpoint_to_cpu(filename, arg_overrides)
>   File "/usr/local/lib/python3.7/dist-packages/fairseq/checkpoint_utils.py", line 232, in load_checkpoint_to_cpu
>     state = _upgrade_state_dict(state)
>   File "/usr/local/lib/python3.7/dist-packages/fairseq/checkpoint_utils.py", line 439, in _upgrade_state_dict
>     cls = REGISTRY["registry"][choice]
> KeyError: 'token_prediction'
> ```

@bg428 Maybe this link can help you.https://github.com/pytorch/fairseq/issues/3256#issuecomment-895702893

**Comment by violet-zct** [comment]
Hey could you git clone my repo and under the root do: pip install --editable ./
