### ISSUE TITLE
Reproduce the result of "Synonym-based Baseline" and   "Ours + Synonym"

### ISSUE THREAD

**Issue by Ricardokevins** [violet-zct/fairseq-detect-hallucination#2]
Hi Awesome work!
I notice that in your paper Synonym is greatly useful in XSUM hallucination detection.
I want to reproduce the "Synonym-based Baseline" and   "Ours + Synonym" result in your paper.
However i can not find the code in the repo . Can you help me or give me some advice?
Thank you very much~

**Comment by violet-zct** [comment]
Hey, sorry for the late reply. For your request, I just pushed a script for the synonym baseline `analysis/xsum_wordnet.py`.

**Comment by Ricardokevins** [comment]
> Hey, sorry for the late reply. For your request, I just pushed a script for the synonym baseline `analysis/xsum_wordnet.py`.

Thank you so much. Help a lot

**Comment by Ricardokevins** [comment]
Hey, I read the code you release.

However I notice that the code read the files : 
```
prefix + "overlap.label"
read_pos_tags_and_tokenizations(os.path.join(root, prefix.lower()+"target.pos"))
```

How to get the files? I search through the preprocess file fold and didnt get any clue.
Thank you for any suggestions!

**Comment by RibinMTC** [comment]
Hi, I have also encountered the same issue. Furthermore, the xsum_wordnet.py script reads the "pos" files on lines 148-149:
` tgt_tok_sents, tgt_tok_pos_tags = read_pos_tags_and_tokenizations(os.path.join(root, prefix.lower()+"target.pos"))
    src_tok_sents, src_tok_pos_tags = read_pos_tags_and_tokenizations(os.path.join(root, prefix.lower()+"source.pos"))
`
How where these files generated?
Best

> Hey, I read the code you release.
> 
> However I notice that the code read the files :
> 
> ```
> prefix + "overlap.label"
> read_pos_tags_and_tokenizations(os.path.join(root, prefix.lower()+"target.pos"))
> ```
> 
> How to get the files? I search through the preprocess file fold and didnt get any clue. Thank you for any suggestions!
