### ISSUE TITLE
Can  'predict_hallucination_mt.py' be used to predict hallucination for summarizaion tasks?

### ISSUE THREAD

**Issue by Lyshc-cgc** [violet-zct/fairseq-detect-hallucination#3]
@violet-zct Hi, I'm sorry to touble u again. As mentioned in REAMDE.ME, we can use 'predict_hallucination_mt.py' directly to predict hallucination.  There is a [XLMRModel](https://github.com/violet-zct/fairseq-detect-hallucination/blob/b1fecee817546368fef8c646776b5be9b651d53c/util_scripts/predict_hallucination_mt.py#L41) for predicting MT hallucination in that script.
 ```
xlmr = XLMRModel.from_pretrained(
    model_path,
    checkpoint_file='checkpoint.pt',
    data_name_or_path=datapath
)
```
Can we use it directly to predict hallucination for summarizaion tasks? Or,  Should we write another script to use roberta model for predicting hallucination in summarization?

**Comment by violet-zct** [comment]
No worries. So XLM-Roberta is a cross-lingually pre-trained model that handles different languages, for English summarization tasks, please use the Roberta model.

**Comment by Lyshc-cgc** [comment]
Appreciate sincerely for your reply!
